"use strict";var d=Object.defineProperty;var w=Object.getOwnPropertyDescriptor;var f=Object.getOwnPropertyNames;var y=Object.prototype.hasOwnProperty;var C=(s,t)=>{for(var i in t)d(s,i,{get:t[i],enumerable:!0})},$=(s,t,i,e)=>{if(t&&typeof t=="object"||typeof t=="function")for(let n of f(t))!y.call(s,n)&&n!==i&&d(s,n,{get:()=>t[n],enumerable:!(e=w(t,n))||e.enumerable});return s};var v=s=>$(d({},"__esModule",{value:!0}),s);var b={};C(b,{default:()=>g});module.exports=v(b);var o=require("obsidian");var l=require("obsidian"),m={inboxFolder:"Literature",duplicateAction:"append_highlight",openAfterCapture:!0,tagPrefix:"literature-note"},u=class extends l.PluginSettingTab{plugin;constructor(t,i){super(t,i),this.plugin=i}display(){let{containerEl:t}=this;t.empty(),t.createEl("h2",{text:"Citation Capture Plugin Settings"}),new l.Setting(t).setName("Literature Notes Folder").setDesc("Vault folder path where captured literature notes will be stored.").addText(i=>i.setPlaceholder("Literature").setValue(this.plugin.settings.inboxFolder).onChange(async e=>{this.plugin.settings.inboxFolder=e.trim()||"Literature",await this.plugin.saveSettings()})),new l.Setting(t).setName("Duplicate Resolution").setDesc("Behavior when capturing a citation with an existing citekey or DOI.").addDropdown(i=>i.addOption("append_highlight","Append new quotes & highlights to existing note").addOption("update","Overwrite entire note with latest metadata").addOption("create_copy","Create separate note with timestamp suffix").setValue(this.plugin.settings.duplicateAction).onChange(async e=>{this.plugin.settings.duplicateAction=e,await this.plugin.saveSettings()})),new l.Setting(t).setName("Open Note After Capture").setDesc("Automatically open the captured literature note in a new tab.").addToggle(i=>i.setValue(this.plugin.settings.openAfterCapture).onChange(async e=>{this.plugin.settings.openAfterCapture=e,await this.plugin.saveSettings()}))}};var p=require("obsidian"),c=class{app;settings;constructor(t,i){this.app=t,this.settings=i}async saveCitation(t,i){let e=(0,p.normalizePath)(i||this.settings.inboxFolder);await this.ensureFolderExists(e);let n=`@${t.citekey}`,a=(0,p.normalizePath)(`${e}/${n}.md`),r=this.app.vault.getAbstractFileByPath(a);if(r instanceof p.TFile)return await this.handleDuplicate(r,t,e,n);let h=this.renderMarkdown(t);return await this.app.vault.create(a,h)}async handleDuplicate(t,i,e,n){switch(this.settings.duplicateAction){case"update":{let a=this.renderMarkdown(i);return await this.app.vault.modify(t,a),t}case"create_copy":{let a=Date.now(),r=(0,p.normalizePath)(`${e}/${n}-${a}.md`),h=this.renderMarkdown(i);return await this.app.vault.create(r,h)}case"append_highlight":default:{if(i.selectedText){let a=await this.app.vault.read(t),r=`

> [!quote] Captured Excerpt (${new Date().toLocaleDateString()})
> ${i.selectedText.replace(/\n/g,`
> `)}
`;await this.app.vault.modify(t,a+r)}return t}}}async ensureFolderExists(t){let i=t.split("/").filter(Boolean),e="";for(let n of i)if(e=e?`${e}/${n}`:n,!this.app.vault.getAbstractFileByPath(e))try{await this.app.vault.createFolder(e)}catch{}}renderMarkdown(t){let i=t.authors.map(r=>`"${r}"`).join(", "),e=t.authors.join(", "),n=t.title.replace(/"/g,'\\"'),a=["---",`citekey: "${t.citekey}"`,`title: "${n}"`,`authors: [${i}]`,`year: ${t.year||""}`,t.doi?`doi: "${t.doi}"`:null,t.journal?`journal: "${t.journal}"`:null,`url: "${t.url}"`,"tags:","  - literature-note","  - academic","---","",`# ${t.title}`,"",`**Authors:** ${e}  `,`**Year:** ${t.year||"n.d."}  `,`**Journal:** ${t.journal||"Academic publication"}  `,`**Link:** [Original Document](${t.url})  `,t.doi?`**DOI:** [${t.doi}](https://doi.org/${t.doi})  `:null,""].filter(r=>r!==null);return t.aiSummary&&a.push("## AI Executive Summary",`> ${t.aiSummary.replace(/\n/g,`
> `)}`,""),t.abstract&&a.push("## Abstract",`> ${t.abstract.replace(/\n/g,`
> `)}`,""),t.selectedText&&a.push("## Highlights & Notes",`> ${t.selectedText.replace(/\n/g,`
> `)}`,""),a.push("## Key Takeaways & Thoughts","- ","","## Citation","```bibtex",t.bibtex||`@misc{${t.citekey},
  title={${t.title}},
  author={${e}}
}`,"```"),a.join(`
`)}};var g=class extends o.Plugin{settings;vaultWriter;async onload(){await this.loadSettings(),this.vaultWriter=new c(this.app,this.settings),this.registerObsidianProtocolHandler("citation",async t=>{try{if(!t.data){new o.Notice("Citation Capture: Received empty protocol payload.");return}let i=decodeURIComponent(t.data),e=JSON.parse(i);e.action==="capture"&&e.data?await this.handleIncomingCitation(e.data,e.settings?.folderPath):new o.Notice(`Citation Capture: Unsupported action "${e.action}".`)}catch(i){console.error("Failed to handle incoming citation protocol URI:",i),new o.Notice(`Citation Capture Error: ${i.message}`)}}),this.addRibbonIcon("book-open","Citation Capture: Open Literature",()=>{new o.Notice(`Literature notes are stored in: ${this.settings.inboxFolder}`)}),this.addSettingTab(new u(this.app,this))}async handleIncomingCitation(t,i){try{let e=await this.vaultWriter.saveCitation(t,i);if(new o.Notice(`Captured: ${e.basename}`),this.settings.openAfterCapture){let n=this.app.workspace.getLeaf(!0);n&&await n.openFile(e)}}catch(e){console.error("Failed to save citation file:",e),new o.Notice(`Failed to save citation: ${e.message}`)}}async loadSettings(){this.settings=Object.assign({},m,await this.loadData())}async saveSettings(){await this.saveData(this.settings),this.vaultWriter=new c(this.app,this.settings)}};
